### ISSUE TITLE
The Pragmatic Programmer

### ISSUE THREAD

**Issue by gustavoferrazfontes** [lincolixavier/clube-do-livro-dev#1]
Está na minha minha wishlist a algum tempo. Seria interessante fazer essa leitura em um grupo.
[Livro na amazon](https://www.amazon.com.br/Pragmatic-Programmer-journey-mastery-Anniversary-ebook/dp/B07VRS84D1/)

**Comment by lincolixavier** [comment]
Boa! Eu não terminei ainda. Mas seria ótimo começar com esse, é basicamente senso comum no nosso mundo. Dave thoma é incrível.
